classstatus/config/routes.rb
Rails.application.routes.draw do
  resources :attendance_records
  # resources :students

  resources :academic_years
  resources :blocks
  resources :courses
  resources :enrollments
  resources :sections
  resources :students do
    collection { post :import }
  end
  resources :terms
  resources :term_names

  devise_for :users

  root to: 'home#index'
end

classstatus/app/models/academic_year.rb
class AcademicYear < ApplicationRecord
end

classstatus/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

classstatus/app/models/attendance_record.rb
class AttendanceRecord < ApplicationRecord
  belongs_to :section
  belongs_to :student

  # XXX: Validate attendance_date?

  enum primary:    { in_class: 'in_class', absent: 'absent', tardy: 'tardy', tardy_10: 'tardy_10' }
  enum secondary:  { lunch_absent: 'lunch_absent', lunch_tardy: 'lunch_tardy', lunch_tardy_10: 'lunch_tardy_10' }
  enum annotation: { called_out: 'called_out', early_release: 'early_release'}
end

classstatus/app/models/block.rb
class Block < ApplicationRecord
end

classstatus/app/models/course.rb
class Course < ApplicationRecord
end

classstatus/app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :student
  belongs_to :section

  def name
    self.section.name
  end

  def short_name
    self.section.abbreviated_name
  end

end

classstatus/app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  belongs_to :academic_year
  belongs_to :term
  belongs_to :block

  has_many :enrollments, inverse_of: :section, dependent: :destroy
  accepts_nested_attributes_for :enrollments
  has_many :students, through: :enrollments

  def name
    self.short_name
  end

  def long_name
    "#{self.short_name} (#{self.term_short_name} - #{self.year_name})"
  end

  def short_name
    "#{self.block_name}: #{self.course_name}"
  end

  def abbreviated_name
    "#{self.block_name}: #{self.course_short_name}"
  end

  def block_name
    self.block.name
  end

  def course_name
    self.course.name
  end

  def course_short_name
    self.course.short_name
  end

  def term_name
    self.term.name
  end

  def term_short_name
    self.term.short_name
  end

  def year_name
    self.academic_year.name
  end
end

classstatus/app/models/student.rb
class Student < ApplicationRecord
  has_many :enrollments, dependent: :destroy

  def name
    self.full_name
  end

  def full_name
    "#{self.preferred_or_given_name} #{self.family_name}"
  end

  def sortable_name
    "#{self.family_name}, #{self.preferred_or_given_name}"
  end

  def short_name
    "#{self.preferred_or_given_name} #{self.family_name[0]}."
  end

  def initials
    "#{self.preferred_or_given_name[0]}#{self.family_name[0]}"
  end

  def preferred_or_given_name
    self.preferred_name ? self.preferred_name : self.given_name
  end

  # Take the attributes in new and merge (update) them into old. Don't change
  # the values of guid and id (id should be unset and a guid mismatch would be
  # a fatal error. Return a copy of old with updates from new.
  #
  # TODO: figure out how to avoid updating the student record if nothing has
  # changed - maybe have a compare routine and make the update conditional.
  def merge_attributes(new)
    merge = Student.new(attributes).attributes
    new.attributes.each do |key, value|
      case key
      when 'guid'       ; puts 'guid: skipped'
      when 'id'         ; puts 'id: skipped'
      when 'created_at' ;
      when 'updated_at' ;
      else
        merge[key] = value if merge.key?(key)
      end
    end
    merge
  end
end

classstatus/app/models/term.rb
class Term < ApplicationRecord
  belongs_to :academic_year
  belongs_to :term_name

  def name
    self.term_name.name
  end

  def short_name
    self.term_name.short_name
  end
end

classstatus/app/models/term_name.rb
class TermName < ApplicationRecord
end

classstatus/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

classstatus/app/helpers/application_helper.rb
module ApplicationHelper

  # Make a table column sortable.
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end

end

classstatus/app/helpers/blocks_helper.rb
module BlocksHelper
end

classstatus/app/helpers/courses_helper.rb
module CoursesHelper
end

classstatus/app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

classstatus/app/helpers/home_helper.rb
module HomeHelper
end

classstatus/app/helpers/sections_helper.rb
module SectionsHelper
end

classstatus/app/helpers/students_helper.rb
module StudentsHelper
end

classstatus/app/helpers/term_names_helper.rb
module TermNamesHelper
end

classstatus/app/helpers/terms_helper.rb
module TermsHelper
end

classstatus/app/views/layouts/_alerts.html.erb
<% btn = '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>' %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <% msg += btn %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>"
      role="alert">
      <%= content_tag :div, msg.html_safe, id: "flash_#{name}", class: 'container' %>
    </div>
  <% end %>
<% end %>

classstatus/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class='container'>

     <%= link_to 'Foundation', root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button"
        data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav mr-auto">

        <li class="nav-item active">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle"
              href="#" id="navbarDropdown" role="button"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Sections',   sections_path,
                  class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Academic Years',   academic_years_path,
                  class: 'dropdown-item' %>
            <%= link_to 'Attendance Record',   attendance_records_path,
                  class: 'dropdown-item' %>
            <%= link_to 'Blocks',           blocks_path,
                  class: 'dropdown-item' %>
            <%= link_to 'Courses',          courses_path,
                  class: 'dropdown-item' %>
            <%= link_to 'Enrollments',      enrollments_path,
                  class: 'dropdown-item' %>
            <%= link_to 'Students',         students_path,
                  class: 'dropdown-item' %>
            <%= link_to 'Terms',            terms_path,
                  class: 'dropdown-item' %>
            <%= link_to 'Term Names',       term_names_path,
                  class: 'dropdown-item' %>
          </div>
        </li>

        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>

      </ul>

      <ul class='nav navbar-nav navbar-right'>
        <% if user_signed_in? %>
          <li class='nav-item'>
            <%= link_to current_user.email, edit_user_registration_path,
              class: 'nav-link' %></li>
          <li class='nav-item'>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete,
              class: 'nav-link' %></li>
        <% else %>
          <li class='nav-item'>
            <%= link_to 'Login', new_user_session_path,
              class: 'nav-link' %></li>
          <li class='nav-item'>
            <%= link_to 'Sign Up', new_user_registration_path,
              class: 'nav-link' %></li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

classstatus/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title><%= content_for?(:title) ? yield(:title) : 'Foundation' %></title>
    <meta name='description'
      content='<%= content_for?(:description) ? yield(:description) : "Foundation" %>'>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <main role='main'>
      <%= render 'layouts/alerts' %>
      <div class='container'>
        <%= content_for?(:content) ? yield(:content) : yield %>
      </div>
    </main>
  </body>
</html>

classstatus/app/views/status/index.html.erb
<!-- apps/views/status/index.html.erb -->

<div class="status-controls">
  <h2>
    Schedule
    Section
  </h2>
</div>

<div class="grid">

  <% max_seats = 30; seat = 0 %>
  <% @enrollments.each do |e| %>
    <% s = e.student %>
    <div class="item" seat="<%= seat %>">
      <div class="item-content">
        <!-- Safe zone, enter your custom markup -->
        <p class="student-name"><%= format_name(s) %></p>
        <p><a href="https://github.com/<%= s.github_user %>"><%= s.github_user %></a></p>
        <!-- Safe zone ends -->
      </div>
    </div>
    <% seat = seat + 1 %>
  <% end %>

  <% until (seat == max_seats) %>
    <div class="item empty-seat" seat="<%= seat %>">
      <div class="item-content">
        <!-- Safe zone, enter your custom markup -->

        <!-- Safe zone ends -->
      </div>
    </div>
    <% seat = seat + 1 %>
  <% end %>

</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/web-animations/2.3.1/web-animations.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.8/hammer.min.js"></script>
<script src="https://unpkg.com/muuri@0.6.3/dist/muuri.min.js"></script>

<script type="text/javascript">
  initGrid();

  function initGrid() {
    var grid = new Muuri('.grid', {
      dragEnabled: true,
      layoutOnInit: false
    }).on('move', function () {
      saveLayout(grid);
    });

    var layout = window.localStorage.getItem('layout');
    if (layout) {
      loadLayout(grid, layout);
    } else {
      grid.layout(true);
    }
  }

  function serializeLayout(grid) {
    var itemIds = grid.getItems().map(function (item) {
      return item.getElement().getAttribute('seat');
    });
    return JSON.stringify(itemIds);
  }

  function saveLayout(grid) {
    var layout = serializeLayout(grid);
    window.localStorage.setItem('layout', layout);
  }

  function loadLayout(grid, serializedLayout) {
    var layout = JSON.parse(serializedLayout);
    var currentItems = grid.getItems();
    var currentItemIds = currentItems.map(function (item) {
      return item.getElement().getAttribute('seat')
    });
    var newItems = [];
    var itemId;
    var itemIndex;

    for (var i = 0; i < layout.length; i++) {
      itemId = layout[i];
      itemIndex = currentItemIds.indexOf(itemId);
      if (itemIndex > -1) {
        newItems.push(currentItems[itemIndex])
      }
    }

    grid.sort(newItems, {layout: 'instant'});
  }
</script>