classstatus/config/routes.rb
Rails.application.routes.draw do
  resources :attendance_records
  # resources :students

  resources :academic_years
  resources :blocks
  resources :courses
  resources :enrollments
  resources :sections
  resources :students do
    collection { post :import }
  end
  resources :terms
  resources :term_names

  devise_for :users

  root to: 'home#index'
end

classstatus/app/models/term_name.rb
class TermName < ApplicationRecord
end

classstatus/app/controllers/term_names_controller.rb
class TermNamesController < ApplicationController
  before_action :set_term_name, only: [:show, :edit, :update, :destroy]

  helper_method :sort_column, :sort_direction

  # GET /term_names
  # GET /term_names.json
  def index
    @term_names = TermName.order(sort_column + " " + sort_direction)
  end

  # GET /term_names/1
  # GET /term_names/1.json
  def show
  end

  # GET /term_names/new
  def new
    @term_name = TermName.new
  end

  # GET /term_names/1/edit
  def edit
  end

  # POST /term_names
  # POST /term_names.json
  def create
    @term_name = TermName.new(term_name_params)

    respond_to do |format|
      if @term_name.save
        format.html { redirect_to term_names_path,
          notice: 'Term name was successfully created.' }
        format.json { render :show, status: :created, location: @term_name }
      else
        format.html { render :new }
        format.json { render json: @term_name.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /term_names/1
  # PATCH/PUT /term_names/1.json
  def update
    respond_to do |format|
      if @term_name.update(term_name_params)
        format.html { redirect_to term_names_path,
          notice: 'Term name was successfully updated.' }
        format.json { render :show, status: :ok, location: @term_name }
      else
        format.html { render :edit }
        format.json { render json: @term_name.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # DELETE /term_names/1
  # DELETE /term_names/1.json
  def destroy
    @term_name.destroy
    respond_to do |format|
      format.html { redirect_to term_names_url, notice: 'Term name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_term_name
      @term_name = TermName.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def term_name_params
      params.require(:term_name).permit(:name, :short_name)
    end

    def sort_column
      TermName.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

classstatus/app/helpers/term_names_helper.rb
module TermNamesHelper
end

classstatus/app/views/term_names/_form.html.erb
<%= simple_form_for(@term_name) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message:
    f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class='form-inputs'>
    <%= f.input :name %>
    <%= f.input :short_name %>
  </div>

  <div class='form-actions'>
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

classstatus/app/views/term_names/edit.html.erb
<h1>Editing Term Name</h1>

<%= render 'form', term_name: @term_name %>

<%= link_to 'Show', @term_name %> |
<%= link_to 'Back', term_names_path %>

classstatus/app/views/term_names/index.html.erb
<h1><span>Term Names</span>
  <span><%= link_to '+', new_term_name_path %></span></h1>

<table class='table table-sm table-striped'>
  <thead class='thead-dark'>
    <tr>
      <th scope='col'><%= sortable "name" %></th>
      <th scope='col'><%= sortable "short_name" %></th>
      <th scope='col' colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @term_names.each do |term_name| %>
      <tr>
        <td><%= term_name.name %></td>
        <td><%= term_name.short_name %></td>
        <td><%= link_to 'Show', term_name %></td>
        <td><%= link_to 'Edit', edit_term_name_path(term_name) %></td>
        <td><%= link_to 'Destroy', term_name, method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

classstatus/app/views/term_names/new.html.erb
<h1>New Term Name</h1>

<%= render 'form', term_name: @term_name %>

<%= link_to 'Back', term_names_path %>

classstatus/app/views/term_names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @term_name.name %>
</p>

<p>
  <strong>Short name:</strong>
  <%= @term_name.short_name %>
</p>

<%= link_to 'Edit', edit_term_name_path(@term_name) %> |
<%= link_to 'Back', term_names_path %>