classstatus/config/routes.rb
Rails.application.routes.draw do
  resources :attendance_records
  # resources :students

  resources :academic_years
  resources :blocks
  resources :courses
  resources :enrollments
  resources :sections
  resources :students do
    collection { post :import }
  end
  resources :terms
  resources :term_names

  devise_for :users

  root to: 'home#index'
end

classstatus/app/models/academic_year.rb
class AcademicYear < ApplicationRecord
end

classstatus/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

classstatus/app/models/attendance_record.rb
class AttendanceRecord < ApplicationRecord
  belongs_to :section
  belongs_to :student

  # XXX: Validate attendance_date?

  enum primary:    { in_class: 'in_class', absent: 'absent', tardy: 'tardy', tardy_10: 'tardy_10' }
  enum secondary:  { lunch_absent: 'lunch_absent', lunch_tardy: 'lunch_tardy', lunch_tardy_10: 'lunch_tardy_10' }
  enum annotation: { called_out: 'called_out', early_release: 'early_release'}
end

classstatus/app/models/block.rb
class Block < ApplicationRecord
end

classstatus/app/models/course.rb
class Course < ApplicationRecord
end

classstatus/app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :student
  belongs_to :section

  def name
    self.section.name
  end

  def short_name
    self.section.abbreviated_name
  end

end

classstatus/app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  belongs_to :academic_year
  belongs_to :term
  belongs_to :block

  has_many :enrollments, inverse_of: :section, dependent: :destroy
  accepts_nested_attributes_for :enrollments
  has_many :students, through: :enrollments

  def name
    self.short_name
  end

  def long_name
    "#{self.short_name} (#{self.term_short_name} - #{self.year_name})"
  end

  def short_name
    "#{self.block_name}: #{self.course_name}"
  end

  def abbreviated_name
    "#{self.block_name}: #{self.course_short_name}"
  end

  def block_name
    self.block.name
  end

  def course_name
    self.course.name
  end

  def course_short_name
    self.course.short_name
  end

  def term_name
    self.term.name
  end

  def term_short_name
    self.term.short_name
  end

  def year_name
    self.academic_year.name
  end
end

classstatus/app/models/student.rb
class Student < ApplicationRecord
  has_many :enrollments, dependent: :destroy

  def name
    self.full_name
  end

  def full_name
    "#{self.preferred_or_given_name} #{self.family_name}"
  end

  def sortable_name
    "#{self.family_name}, #{self.preferred_or_given_name}"
  end

  def short_name
    "#{self.preferred_or_given_name} #{self.family_name[0]}."
  end

  def initials
    "#{self.preferred_or_given_name[0]}#{self.family_name[0]}"
  end

  def preferred_or_given_name
    self.preferred_name ? self.preferred_name : self.given_name
  end

  # Take the attributes in new and merge (update) them into old. Don't change
  # the values of guid and id (id should be unset and a guid mismatch would be
  # a fatal error. Return a copy of old with updates from new.
  #
  # TODO: figure out how to avoid updating the student record if nothing has
  # changed - maybe have a compare routine and make the update conditional.
  def merge_attributes(new)
    merge = Student.new(attributes).attributes
    new.attributes.each do |key, value|
      case key
      when 'guid'       ; puts 'guid: skipped'
      when 'id'         ; puts 'id: skipped'
      when 'created_at' ;
      when 'updated_at' ;
      else
        merge[key] = value if merge.key?(key)
      end
    end
    merge
  end
end

classstatus/app/models/term.rb
class Term < ApplicationRecord
  belongs_to :academic_year
  belongs_to :term_name

  def name
    self.term_name.name
  end

  def short_name
    self.term_name.short_name
  end
end

classstatus/app/models/term_name.rb
class TermName < ApplicationRecord
end

classstatus/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

classstatus/app/controllers/attendance_records_controller.rb
class AttendanceRecordsController < ApplicationController
  before_action :set_attendance_record, only: [:show, :edit, :update, :destroy]

  helper_method :sort_column, :sort_direction

  # GET /attendance_records
  def index
    @attendance_records = AttendanceRecord.order(sort_column + " " + sort_direction)
  end

  # GET /attendance_records/1
  def show
  end

  # GET /attendance_records/new
  def new
    @attendance_record = AttendanceRecord.new
  end

  # GET /attendance_records/1/edit
  def edit
  end

  # POST /attendance_records
  def create
    @attendance_record = AttendanceRecord.new(attendance_record_params)

    if @attendance_record.save
      redirect_to @attendance_record,
        notice: 'Attendance record was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /attendance_records/1
  def update
    if @attendance_record.update(attendance_record_params)
      redirect_to @attendance_record,
        notice: 'Attendance record was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /attendance_records/1
  def destroy
    @attendance_record.destroy
    redirect_to attendance_records_url,
      notice: 'Attendance record was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance_record
      @attendance_record = AttendanceRecord.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def attendance_record_params
      params.require(:attendance_record).permit(
        :section_id, :student_id, :attendance_date,
        :primary, :secondary, :annotations)
    end

    # Helpers for sortable table columns.
    def sort_column
      AttendanceRecord.column_names.include?(params[:sort]) ? params[:sort] : 'attendance_date'
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
    end
end

classstatus/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
end

classstatus/app/helpers/application_helper.rb
module ApplicationHelper

  # Make a table column sortable.
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end

end

classstatus/app/helpers/attendance_records_helper.rb
module AttendanceRecordsHelper
end

classstatus/app/helpers/blocks_helper.rb
module BlocksHelper
end

classstatus/app/helpers/courses_helper.rb
module CoursesHelper
end

classstatus/app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

classstatus/app/helpers/home_helper.rb
module HomeHelper
end

classstatus/app/helpers/sections_helper.rb
module SectionsHelper
end

classstatus/app/helpers/students_helper.rb
module StudentsHelper
end

classstatus/app/helpers/term_names_helper.rb
module TermNamesHelper
end

classstatus/app/helpers/terms_helper.rb
module TermsHelper
end

classstatus/app/views/attendance_records/_form.html.erb
<%= simple_form_for(@attendance_record) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message:
    f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class='form-inputs'>
    <%= f.association :section %>
    <%= f.association :student %>
    <%= f.input :attendance_date %>
    <%= f.collection_radio_buttons :primary,
      AttendanceRecord.primaries, :second, :first   %>
    <%= f.collection_radio_buttons :secondary,
      AttendanceRecord.secondaries, :second, :first %>
    <%= f.collection_radio_buttons :annotation,
      AttendanceRecord.annotations, :second, :first %>
  </div>

  <div class='form-actions'>
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

classstatus/app/views/attendance_records/edit.html.erb
<h1>Editing Attendance Record</h1>

<%= render 'form', attendance_record: @attendance_record %>

<%= link_to 'Show', @attendance_record %> |
<%= link_to 'Back', attendance_records_path %>

classstatus/app/views/attendance_records/index.html.erb
<h1><span>Attendance Records</span>
  <span><%= link_to '+', new_attendance_record_path %></span></h1>

<table class='table table-sm table-striped'>
  <thead class='thead-dark'>
    <tr>
      <th scope='row'>Section</th>
      <th scope='row'>Student</th>
      <th scope='row'>Attendance date</th>
      <th scope='row'>Primary</th>
      <th scope='row'>Secondary</th>
      <th scope='row'>Annotation</th>
      <th scope='row' colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendance_records.each do |attendance_record| %>
      <tr>
        <td><%= attendance_record.section_id %></td>
        <td><%= attendance_record.student_id %></td>
        <td><%= attendance_record.attendance_date %></td>
        <td><%= attendance_record.primary %></td>
        <td><%= attendance_record.secondary %></td>
        <td><%= attendance_record.annotation %></td>
        <td><%= link_to 'Show', attendance_record %></td>
        <td><%= link_to 'Edit', edit_attendance_record_path(attendance_record) %></td>
        <td><%= link_to 'Destroy', attendance_record,
          method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

classstatus/app/views/attendance_records/new.html.erb
<h1>New Attendance Record</h1>

<%= render 'form', attendance_record: @attendance_record %>

<%= link_to 'Back', attendance_records_path %>

classstatus/app/views/attendance_records/show.html.erb
<p>
  <strong>Section:</strong>
  <%= @attendance_record.section_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @attendance_record.student_id %>
</p>

<p>
  <strong>Attendance date:</strong>
  <%= @attendance_record.attendance_date %>
</p>

<p>
  <strong>Primary:</strong>
  <%= @attendance_record.primary %>
</p>

<p>
  <strong>Secondary:</strong>
  <%= @attendance_record.secondary %>
</p>

<p>
  <strong>Annotation:</strong>
  <%= @attendance_record.annotation %>
</p>

<%= link_to 'Edit', edit_attendance_record_path(@attendance_record) %> |
<%= link_to 'Back', attendance_records_path %>