classstatus/config/routes.rb
Rails.application.routes.draw do
  resources :attendance_records
  # resources :students

  resources :academic_years
  resources :blocks
  resources :courses
  resources :enrollments
  resources :sections
  resources :students do
    collection { post :import }
  end
  resources :terms
  resources :term_names

  devise_for :users

  root to: 'home#index'
end

classstatus/app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  belongs_to :academic_year
  belongs_to :term
  belongs_to :block

  has_many :enrollments, inverse_of: :section, dependent: :destroy
  accepts_nested_attributes_for :enrollments
  has_many :students, through: :enrollments

  def name
    self.short_name
  end

  def long_name
    "#{self.short_name} (#{self.term_short_name} - #{self.year_name})"
  end

  def short_name
    "#{self.block_name}: #{self.course_name}"
  end

  def abbreviated_name
    "#{self.block_name}: #{self.course_short_name}"
  end

  def block_name
    self.block.name
  end

  def course_name
    self.course.name
  end

  def course_short_name
    self.course.short_name
  end

  def term_name
    self.term.name
  end

  def term_short_name
    self.term.short_name
  end

  def year_name
    self.academic_year.name
  end
end

classstatus/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  helper_method :sort_column, :sort_direction

  # GET /sections
  def index
    @sections = Section.order(sort_column + " " + sort_direction)
  end

  # GET /sections/1
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  def create
    @section = Section.new(section_params)

    if @section.save
      redirect_to sections_path,
        notice: 'Section was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /sections/1
  def update
    if @section.update(section_params)
      redirect_to sections_path,
        notice: 'Section was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /sections/1
  def destroy
    @section.destroy
    redirect_to sections_url,
      notice: 'Section was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def section_params
      params.require(:section).permit(:course_id, :academic_year_id, :term_id, :block_id)
    end

    # Helpers for sortable table columns.
    def sort_column
      Section.column_names.include?(params[:sort]) ? params[:sort] : 'block_id'
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
    end
end

classstatus/app/helpers/sections_helper.rb
module SectionsHelper
end

classstatus/app/views/sections/_form.html.erb
<%= simple_form_for(@section) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message:
    f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class='form-inputs'>
    <%= f.association :course %>
    <%= f.association :academic_year %>
    <%= f.association :term %>
    <%= f.association :block %>
  </div>

  <div class='form-actions'>
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

classstatus/app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

classstatus/app/views/sections/index.html.erb
<h1><span>Sections</span>
  <span><%= link_to '+', new_section_path %></span></h1>

<table class='table table-sm table-striped'>
  <thead class='thead-dark'>
    <tr>
      <th scope='row'><%= sortable 'course' %></th>
      <th scope='row'><%= sortable 'academic_year' %></th>
      <th scope='row'><%= sortable 'term' %></th>
      <th scope='row'><%= sortable 'block' %></th>
      <th scope='row' colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.course_name %></td>
        <td><%= section.year_name %></td>
        <td><%= section.term_name %></td>
        <td><%= section.block_name %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section,
          method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

classstatus/app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

classstatus/app/views/sections/show.html.erb
<h3><%= @section.long_name %></h3>

<%= simple_form_for @section do |s| %>
  <%= s.simple_fields_for :enrollment do |e| %>
    <%= e.input :student %>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>